### ISSUE TITLE
svm遇到问题

### ISSUE THREAD

**Issue by jiushiainiaizheni** [shibing624/text-classifier#1]
你好，我在使用svm模型的时候遇到了无法解决的问题，报错入下。
AttributeError: predict_proba is not available when  probability=False
![image](https://user-images.githubusercontent.com/38657118/39124724-10f31cac-472f-11e8-9934-45567845b27c.png)
请问如何解决

**Comment by shibing624** [comment]
已经解决，更新evaluate下的predict即可。详见最新代码，更新链接：https://github.com/shibing624/text-classifier/commit/c0f0b1882b9ec93110c438d3ed594dcc4782c575
